# Generated by Django 5.1.2 on 2025-01-09 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('employer', 'Employer'), ('manager', 'Manager')], default='seeker', max_length=10),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Company Location')),
                ('company_website', models.URLField(blank=True, verbose_name='Company Website')),
                ('company_description', models.TextField(blank=True, verbose_name='Company Description')),
                ('phone', models.CharField(blank=True, help_text='Include country code (e.g., +1)', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(blank=True, verbose_name='Twitter Link')),
                ('google_link', models.URLField(blank=True, verbose_name='Google Link')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='LinkedIn Link')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Founded Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
            },
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('resume', models.FileField(blank=True, upload_to='resumes/', verbose_name='Resume')),
                ('skills', models.TextField(blank=True, verbose_name='Skills')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('professional_title', models.CharField(blank=True, max_length=255, verbose_name='Professional Title')),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Current Salary')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Expected Salary')),
                ('phone', models.CharField(blank=True, help_text='Include country code (e.g., +1)', max_length=15, verbose_name='Phone Number')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seeker Profile',
                'verbose_name_plural': 'Seeker Profiles',
            },
        ),
    ]
