# Generated by Django 5.1.2 on 2025-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_employerprofile_seekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='media/resumes/', verbose_name='Resume'),
        ),
    ]
