# Generated by Django 5.1.2 on 2025-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_seekerprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Include country code (e.g., +88)', max_length=15, verbose_name='Phone Number'),
        ),
    ]
