# Generated by Django 5.1.2 on 2025-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_seekerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('employer', 'Employer'), ('manager', 'Manager'), ('candidate', 'candidate')], default='seeker', max_length=10),
        ),
    ]
