# Generated by Django 5.1.2 on 2025-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company_logos/', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/seeker_logos/', verbose_name='seeker image'),
        ),
    ]
