# Generated by Django 5.1.2 on 2025-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employerprofile_logo_seekerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='media/default/default_logo.png', null=True, upload_to='media/company_logos/', verbose_name='Company Logo'),
        ),
    ]
