# Generated by Django 5.1.2 on 2025-03-10 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employerprofile_logo'),
        ('seeker', '0010_alter_resume_email_alter_resume_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='my_resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.resume', verbose_name='Resume'),
        ),
    ]
