# Generated by Django 5.1.2 on 2025-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seekerprofile_my_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Include country code (e.g., +880)', max_length=15, verbose_name='Phone Number'),
        ),
    ]
