# Generated by Django 5.1.2 on 2025-01-11 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='area_pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='availability_to_join',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hometown',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
