# Generated by Django 5.1.2 on 2025-01-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_alter_resume_area_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
