# Generated by Django 5.1.2 on 2025-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='availability_to_join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
