# Generated by Django 5.1.2 on 2025-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_alter_resume_availability_to_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
