# Generated by Django 5.1.2 on 2025-01-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_alter_resume_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_name_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
