# Generated by Django 5.1.2 on 2025-02-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0007_certification_certification_name_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='version',
        ),
    ]
