# Generated by Django 5.1.2 on 2025-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0008_remove_skill_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, default='media/default/default_logo.png', null=True, upload_to='media/seeker_image/', verbose_name='Seeker Image'),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Professional Title'),
        ),
    ]
