# Generated by Django 5.0 on 2025-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0012_alter_resume_desired_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('related_skills', models.TextField(help_text='Enter skills separated by commas, e.g. HTML, CSS, JavaScript')),
                ('cost', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('image', models.ImageField(blank=True, default='default/resource_default.png', help_text='Optional: Upload an image or logo for this resource', null=True, upload_to='learning_resources/')),
            ],
        ),
    ]
