# Generated by Django 5.0 on 2025-11-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0013_learningresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the learning resource', null=True),
        ),
    ]
