# Generated by Django 4.2.18 on 2025-11-13 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0014_learningresource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
