# Generated by Django 5.0 on 2025-11-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0015_learningresource_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('experience', 'Experience Skill'), ('desire', 'Desire Skill')], default='experience', max_length=20),
        ),
    ]
