# Generated by Django 5.0 on 2025-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0016_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='last_used_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
