# Generated by Django 5.1.2 on 2025-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary_range',
            field=models.CharField(blank=True, default='Negotiable', max_length=200, null=True),
        ),
    ]
