# Generated by Django 5.1.2 on 2025-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_jobpost_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='expected_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, upload_to='media/apply/resumes/', verbose_name='Resume'),
        ),
    ]
