# Generated by Django 5.1.2 on 2025-03-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_jobapplication_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='age_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='applicant_photo_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_industry_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='cv_receive_method',
            field=models.CharField(blank=True, choices=[('Online CV/Resume', 'Online CV/Resume'), ('Email Attachment', 'Email Attachment'), ('Walk-in Interview', 'Walk-in Interview'), ('Hard Copy CV', 'Hard Copy CV')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='educational_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='exclusive_job',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_required',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts_category', to='jobboard.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_level',
            field=models.CharField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Top Level', 'Top Level')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contractual', 'Contractual'), ('Internship', 'Internship')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='no_of_vacancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
