# Generated by Django 5.1.2 on 2025-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_alter_jobpost_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='others_qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
