# Generated by Django 5.1.2 on 2025-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_jobpost_others_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'active'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
