# Generated by Django 5.1.2 on 2025-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0007_alter_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('published ', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
