# Generated by Django 5.1.2 on 2025-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0009_alter_jobpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog_images/')),
                ('categories', models.ManyToManyField(blank=True, to='jobboard.blogcategory')),
            ],
        ),
    ]
