# Generated by Django 5.1.2 on 2025-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
