# Generated by Django 5.1.2 on 2025-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0011_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='media/default/blog.jpg', null=True, upload_to='media/blog_images/'),
        ),
    ]
